# Generated by Django 2.1.2 on 2018-11-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181106_0646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipovivienda',
            options={'verbose_name': 'Tipo Vivienda', 'verbose_name_plural': 'Tipos Viviendas'},
        ),
    ]
